# Generated by Django 3.1.5 on 2022-03-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_topic', models.CharField(db_index=True, max_length=200)),
                ('number_in_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Probl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_txt', models.TextField(blank=True, default='', null=True)),
                ('solution_txt', models.TextField(blank=True, default='', null=True)),
                ('hint_txt', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('complexity', models.IntegerField(blank=True, default=0, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('result_full', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ege', models.IntegerField(blank=True, default=0, null=True)),
                ('place_ege', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tip_ege', models.IntegerField(blank=True, default=0, null=True)),
                ('gkey', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('number_task', models.IntegerField(blank=True, default=0, null=True)),
                ('variant', models.IntegerField(blank=True, default=0, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name_potok', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('topic', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='main.topic')),
            ],
            options={
                'verbose_name': 'probl',
                'verbose_name_plural': 'probls',
            },
        ),
    ]
