# Generated by Django 3.1.5 on 2022-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='probl',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
