# Generated by Django 3.1.5 on 2022-03-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_probl_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exam',
            new_name='Examm',
        ),
    ]
