# Generated by Django 3.1.5 on 2022-03-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220329_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examm',
        ),
    ]
