# Generated by Django 3.1.5 on 2022-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='tip_ege',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
