# Generated by Django 3.1.5 on 2022-04-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_bimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bimg',
        ),
    ]
