# Generated by Django 3.1.5 on 2022-04-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_bimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('img1', models.ImageField(blank=True, default='', null=True, upload_to='condition')),
                ('img2', models.ImageField(blank=True, default='', null=True, upload_to='condition')),
            ],
        ),
    ]
