# Generated by Django 3.1.5 on 2022-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='probl',
            name='school_class',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
