# Generated by Django 3.1.5 on 2022-04-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_probl_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mett',
            field=models.IntegerField(default=0),
        ),
    ]
