# Generated by Django 3.1.5 on 2022-08-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_topic_mett'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tip_top',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
