# Generated by Django 3.1.5 on 2022-08-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_topic_tip_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='probl',
            name='nopor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
