# Generated by Django 3.1.5 on 2022-10-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_probl_nopor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_theme', models.CharField(db_index=True, max_length=200)),
                ('content_theme', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
