# Generated by Django 3.1.5 on 2022-11-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smailic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_rec', models.IntegerField(default=0)),
                ('sm', models.ImageField(default='', upload_to='smile')),
                ('ms', models.ImageField(default='', upload_to='ange')),
            ],
        ),
    ]
