# Generated by Django 3.1.5 on 2023-01-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_topic_backdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='probl',
            name='exam_tip',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
