# Generated by Django 3.1.5 on 2023-01-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_probl_exam_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='mett1',
            field=models.IntegerField(default=0),
        ),
    ]
