# Generated by Django 3.1.5 on 2023-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20230329_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bpdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_tip', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('gkey', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('dpdf', models.BinaryField(blank=True, default=0, null=True)),
            ],
        ),
    ]
