# Generated by Django 3.1.5 on 2023-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpdf',
            name='dpdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
