# Generated by Django 3.1.5 on 2023-10-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20231010_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpdf',
            name='dpdf',
            field=models.BinaryField(default=b'"\'"'),
        ),
    ]
