# Generated by Django 3.1.5 on 2023-10-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20231010_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpdf',
            name='dpdf',
        ),
    ]
