# Generated by Django 3.1.5 on 2023-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_bpdf_dpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpdf',
            name='ppdf',
            field=models.FileField(default='', upload_to='fpdf'),
        ),
    ]
