# Generated by Django 3.1.5 on 2023-10-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_bpdf_ppdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpdf',
            name='ppdf',
        ),
        migrations.AddField(
            model_name='bpdf',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
