# Generated by Django 3.1.5 on 2023-10-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20231012_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpdf',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
